# Generated by Django 5.2.3 on 2025-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_remove_fotografia_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
    ]
