# Generated by Django 5.2.3 on 2025-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='tag',
            field=models.CharField(choices=[('Nebulosa', 'Nebulosa'), ('Estrela', 'Estrela'), ('Galáxia', 'Galáxia'), ('Planeta', 'Planeta'), ('Lua', 'Lua')], default='', max_length=100),
        ),
    ]
